administrator/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from .views import *

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('administrator:requests')), name='home'),
    url(r'^pedidos/$', order_list_view, name='requests'),
    url(r'^pedido-detalle/(?P<req>\d+)/$', detail_order_view, name='request__detail'),
    url(r'^compradores/$', buyer_list_view, name='buyers'),
    url(r'^compradores/agregar/$', buyer_add_view, name='buyers__add'),
    url(r'^compradores/editar/(?P<buyerid>\d+)/$', buyer_update_view, name='buyers__edit'),
    url(r'^compradores/borrar/(?P<user>\d+)/$', buyer_delete_view, name='buyers__delete'),
    url(r'^productores/$', producer_list_view, name='producers'),
    url(r'^productores/agregar/$', producer_add_view, name='producer__add'),
    url(r'^productores/editar/(?P<prod>\d+)/$', producer_update_view, name='producer__edit'),
    url(r'^productores/borrar/(?P<user>\d+)/$', producer_delete_view, name='producer__delete'),
    url(r'^productos/$', product_list_view, name='products'),
    url(r'^productos/agregar/$', product_add_view, name='product__add'),
    url(r'^productos/editar/(?P<cod>\d+)/$', product_update_view, name='product__edit'),
    url(r'^productos/borrar/(?P<cod>\d+)/$', product_delete_view, name='product__delete'),
    url(r'^cambio-contrasena/$', change_password_view, name='change_password')
]

buyer/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', orders_view, name='orders'),
    url(r'^micuenta/$', profile_view, name='home'),
]

comproagro/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from administrator import urls as admin_urls
from store import urls as store_urls
from website import urls as website_urls
from buyer import urls as buyer_urls



urlpatterns = [
    url(r'^', include(website_urls, namespace='website')),
    url(r'^tienda/', include(store_urls, namespace='store')),
    url(r'^administrador/', include(admin_urls, namespace='administrator')),
    url(r'^comprador/', include(buyer_urls, namespace='buyer')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    url(r'^salir/$', website_urls.logout_view, name='logout'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

administrator/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


class TimeStampModel(models.Model):
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True

class UserManagerCustom(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        return self._create_user(email, password, True, **extra_fields)


@python_2_unicode_compatible
class UserModel(AbstractBaseUser, TimeStampModel):
    email = models.EmailField(
        max_length=255,
        unique=True,
        verbose_name='Correo electrónico'
    )
    profile = models.CharField(
        max_length=255,
        blank=True
    )
    is_superuser = models.BooleanField(
        default=False
    )

    objects = UserManagerCustom()

    REQUIRED_FIELDS = ['password']
    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        db_table = 'user'

    def __str__(self):
        return '%s' % self.email


@python_2_unicode_compatible
class Buyer(TimeStampModel):
    user = models.OneToOneField(
        UserModel,
        on_delete=models.PROTECT
    )
    name = models.CharField(
        max_length=255
    )
    identification = models.CharField(
        max_length=255
    )
    address = models.CharField(
        max_length=255
    )
    phone = models.CharField(
        max_length=255
    )
    city = models.CharField(
        max_length=255
    )
    email_notifications = models.BooleanField(
        default=False
    )
    product_wanted = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    quantity_wanted = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    contact_name = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    contact_email = models.EmailField(
        max_length=255,
        blank=True,
        null=True
    )
    contact_phone = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Comprador'
        verbose_name_plural = 'Compradores'
        db_table = 'buyer'

    def __str__(self):
        return '%s' % self.name_buyer


@python_2_unicode_compatible
class Producer(TimeStampModel):
    user = models.OneToOneField(
        UserModel,
        on_delete=models.PROTECT
    )
    name = models.CharField(
        max_length=255
    )
    identification = models.CharField(
        max_length=255
    )
    address = models.CharField(
        max_length=255
    )
    phone = models.CharField(
        max_length=255
    )
    city = models.CharField(
        max_length=255
    )
    email_notifications = models.BooleanField(
        default=False
    )
    produced_products = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    produced_quantity = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    production_time = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Productor'
        verbose_name_plural = 'Productores'
        db_table = 'producer'

    def __str__(self):
        return '%s' % self.name_producer

store/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from administrator.models import TimeStampModel, Buyer, Producer


SELL_UNIT = (
    ('kilo', 'Kilo'),
    ('libra', 'Libra'),
    ('caja', 'Caja'),
    ('unidad', 'Unidad'),
    ('arroba', 'Arroba'),
    ('bulto', 'Bulto'),
)
STATE_ORDER = (
    ('cancelado', 'Cancelado'),
    ('en proceso', 'En proceso'),
    ('enviado', 'Enviado'),
    ('pendiente', 'Pendiente'),
)


def upload_product_image(request, filename):
    return filename


@python_2_unicode_compatible
class Product(TimeStampModel):

    name = models.CharField(
        max_length=255,
    )
    variety = models.CharField(
        max_length=255
    )
    category = models.CharField(
        max_length=255
    )
    image = models.ImageField(
        upload_to=upload_product_image
    )
    sell_unit = models.CharField(
        max_length=16,
        choices=SELL_UNIT,
        default='kilo'
    )
    min_selling = models.PositiveIntegerField()
    price = models.FloatField()
    features = models.TextField()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        db_table = 'product'

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class Order(TimeStampModel):
    buyer = models.ForeignKey(
        Buyer,
        on_delete=models.PROTECT
    )
    producer = models.ForeignKey(
        Producer,
        null=True,
        blank=True
    )
    code = models.CharField(
        max_length=8
    )
    ship = models.FloatField()
    fee = models.FloatField()
    subtotal = models.FloatField()
    comments = models.TextField()
    state = models.CharField(
        max_length=50,
        choices=STATE_ORDER,
        default='pendiente'
    )
    shipping_date = models.DateField(
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        db_table = 'order'

    def __str__(self):
        return '%s' % self.code


@python_2_unicode_compatible
class OrderItem(models.Model):
    order = models.ForeignKey(
        Order
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT
    )
    quantity = models.PositiveIntegerField()
    subtotal = models.FloatField(
        blank=True
    )

    class Meta:
        verbose_name = 'Item pedido'
        verbose_name_plural = 'Items pedido'
        db_table = 'order_item'

    def __str__(self):
        return '%s-%s' % (self.order.code, self.product.name)

store/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms

from .models import Product, SELL_UNIT


class ProductForm(forms.ModelForm):
    sell_unit = forms.CharField(
        widget=forms.Select(
            choices=SELL_UNIT,
            attrs={
                'class': 'middle'
            }
        )
    )

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nombre'}),
            'variety': forms.TextInput(attrs={'placeholder': 'Variedad'}),
            'category': forms.TextInput(attrs={'placeholder': 'Categoria'}),
            'image': forms.FileInput(attrs={'class': 'jimage'}),
            'min_selling': forms.TextInput(attrs={
                'placeholder': 'Cantidad mínima', 'class': 'middle'
            }),
            'price': forms.TextInput(attrs={'placeholder': 'Precio'}),
            'features': forms.Textarea(attrs={'placeholder': 'Descripción del producto'})
        }
        labels = {
            'name': 'Nombre',
            'variety': 'Variedad',
            'category': 'Categoria',
            'image': 'Agregar imagen',
            'min_selling': 'Compra mínima',
            'price': 'Precio',
            'features': 'Descripción'
        }


class DeleteProductForm(forms.Form):
    prod = forms.CharField(
        max_length=50
    )

administrator/templates/buyer-add.html
{% extends 'base_administrator.html' %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <div class="buyer__form-container">
            <form action="." class="white" method="post">
                {% csrf_token %}
                <div class="buyer__form-container--left">
                    <h2>Información personal</h2>
                    <div class="form__item form__item--white">
                        {{ formp.name.label_tag }}{{ formp.name }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ form.email.label_tag }}{{ form.email }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ form.password.label_tag }}{{ form.password }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.identification.label_tag }}{{ formp.identification }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.phone.label_tag }}{{ formp.phone }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.product_wanted.label_tag }}{{ formp.product_wanted }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.quantity_wanted.label_tag }}{{ formp.quantity_wanted }}
                    </div>
                    <button type="submit" class="btn--app btn--app--left">Guardar</button>
                </div>
                <div class="buyer__form-container--right">
                    <h2>Información de envio</h2>
                    <div class="form__item form__item--white">
                        {{ formp.city.label_tag }}{{ formp.city }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.address.label_tag }}{{ formp.address }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.city.label_tag }}{{ formp.city }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.contact_phone.label_tag }}{{ formp.contact_phone }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.contact_name.label_tag }}{{ formp.contact_name }}
                    </div>

                </div>

            </form>
        </div>
    </div>
{% endblock %}

administrator/templates/buyer-delete.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% block extraCSS %}
{#    <link rel="stylesheet" href="{% static 'css/vendor/image.upload.css' %}"/>#}
{% endblock %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <h2 class="center">¿Está seguro que desea borrar el comprador {{ buyer.name }}</h2>
        <br/>
        <div class="product__form-container">
            <form action="." method="post" class="white">
                {% csrf_token %}
                <input type="hidden" name="user" id="id_user" value="{{ buyer.user.id }}"/>
                <a href="#" onclick="window.history.back(); return false;" class="btn btn--app">No</a><button type="submit" class="btn btn--app">Borrar</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block extraJS %}

{% endblock %}

administrator/templates/buyer-detail.html
{% extends 'base_administrator.html' %}
{% load humanize %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <div class="buyer__form-container">
            <form action="." class="white" method="post">
                {% csrf_token %}
                <div class="buyer__form-container--left">
                    <h2>Información personal</h2>
                    <div class="form__item form__item--white">
                        {{ formp.name.label_tag }}{{ formp.name }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ form.email.label_tag }}{{ form.email }}
                    </div>
{#                    <div class="form__item form__item--white">#}
{#                        {{ form.password.label_tag }}{{ form.password }}#}
{#                    </div>#}
                    <div class="form__item form__item--white">
                        {{ formp.identification.label_tag }}{{ formp.identification }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.phone.label_tag }}{{ formp.phone }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.product_wanted.label_tag }}{{ formp.product_wanted }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.quantity_wanted.label_tag }}{{ formp.quantity_wanted }}
                    </div>
                    <button type="submit" class="btn--app btn--app--left">Guardar</button>
                </div>
                <div class="buyer__form-container--right">
                    <h2>Información de envio</h2>
                    <div class="form__item form__item--white">
                        {{ formp.city.label_tag }}{{ formp.city }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.address.label_tag }}{{ formp.address }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.city.label_tag }}{{ formp.city }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.contact_phone.label_tag }}{{ formp.contact_phone }}
                    </div>
                    <div class="form__item form__item--white">
                        {{ formp.contact_name.label_tag }}{{ formp.contact_name }}
                    </div>

                </div>

            </form>
        </div>
        <h2>Sus pedidos</h2>
            {% for p in buyer.order_set.all %}
                {% if forloop.first %}
                    <table>
                        <thead>
                            <tr class="fifth">
                                <th>Referencia del pedido</th>
                                <th>Fecha de entrega</th>
                                <th>Precio total</th>
{#                                <th>Método de pago</th>#}
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tbody>
                {% endif %}
                            <tr class="fifth">
                                <td><a href="{% url 'administrator:request__detail' p.id %}">{{ p.code }}</a></td>
                                {# TODO: include var date shipping #}
                                <td>{% if p.shipping_date %}{{ p.shipping_date }}{% else %}Por definir{% endif %}</td>
                                <td>$ {{ p.subtotal|intcomma }}</td>
{#                                <td></td>#}
                                <td>{{ p.state }}</td>
                            </tr>
                {% if forloop.last %}
                        </tbody>
                    </table>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

administrator/templates/buyers-list.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <h2>Estos son los compradores</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="message message--info">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% for b in list_buyers %}
            {% if forloop.first %}
                <table>
                    <thead>
                        <tr class="fourth">
                            <th>Nombre</th>
                            <th>Número de pedidos</th>
                            <th>Fecha del último pedido</th>
                            <th>Estado de último pedido</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
            {% endif %}
                        <tr class="fourth">
                            <td><a href="{% url 'administrator:buyers__edit' b.id %}">{{ b.name }}</a></td>
                            <td class="center">{{ b.order_set.all|length }}</td>
                            <td>{% for i in b.order_set.all %}{% if forloop.last %}{{ i.created|date:"d/m/Y" }}{% endif %}{% endfor %}</td>
                            <td>{% for i in b.order_set.all %}{% if forloop.last %}{{ i.state|capfirst }}{% endif %}{% endfor %}</td>
                            <td class="center"><a href="{% url 'administrator:buyers__delete' b.user.id %}"><img src="{% static 'images/delete_icon.png' %}" alt=""/></a></td>
                        </tr>
            {% if forloop.last %}
                    </tbody>
                </table>
            {% endif %}
        {% empty %}
            <h3 class="center">No hay compradores registrados</h3>
        {% endfor %}
    </div>
{% endblock %}

administrator/templates/change_password.html
{% extends 'base_administrator.html' %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <div class="main-content__request__head">
            <h2 class="center">Cambia la contraseña</h2>

        </div>
        <div class="password-change__form-container">
            <form action="." method="post" class="transparent">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form__item form__item--white">
                        {{ field.label_tag }}{{ field }}
                    </div>
                {% endfor %}
                <button class="btn--app" type="submit">Guardar</button>
            </form>
        </div>
    </div>
{% endblock %}

administrator/templates/producer-delete.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% block extraCSS %}
{#    <link rel="stylesheet" href="{% static 'css/vendor/image.upload.css' %}"/>#}
{% endblock %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <h2 class="center">¿Está seguro que desea borrar el productor {{ producer.name}}</h2>
        <br/>
        <div class="product__form-container">
            <form action="." method="post" class="white">
                {% csrf_token %}
                <input type="hidden" name="user" id="id_user" value="{{ producer.user.id }}"/>
                <a href="#" onclick="window.history.back(); return false;" class="btn btn--app">No</a><button type="submit" class="btn btn--app">Borrar</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block extraJS %}

{% endblock %}

administrator/templates/producers-list.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <div class="main-content__request__head">
            <h2 class="center">Estos son los productores</h2>
            <a href="{% url 'administrator:producer__add' %}" class="btn btn--app">Agregar productor</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="message message--info">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% for p in list_producer %}
            {% if forloop.first %}
                <table>
                    <thead>
                        <tr class="third">
                            <th>Nombre</th>
                            <th>Correo</th>
                            <th>Teléfono</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
            {% endif %}
                    <tr>
                        <td><a href="{% url 'administrator:producer__edit' p.id %}">{{ p.name }}</a></td>
                        <td>{{ p.user.email }}</td>
                        <td>{{ p.phone }}</td>
                        <td class="center"><a href="{% url 'administrator:producer__delete' p.user.id %}"><img src="{% static 'images/delete_icon.png' %}" alt=""/></a></td>
                    </tr>
            {% if forloop.last %}
                    </tbody>
                </table>
            {% endif %}
        {% empty %}
            <h3 class="center">No hay productores registrados</h3>
        {% endfor %}
    </div>
{% endblock %}

administrator/templates/product-delete.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% block extraCSS %}
{#    <link rel="stylesheet" href="{% static 'css/vendor/image.upload.css' %}"/>#}
{% endblock %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <h2 class="center">¿Está seguro que desea borrar el producto {{ product.name }}</h2>
        <br/>
        <div class="product__form-container">
            <form action="." method="post" class="white">
                {% csrf_token %}
                <input type="hidden" name="prod" id="id_prod" value="{{ product.id }}"/>
                <a href="#" onclick="window.history.back(); return false;" class="btn btn--app">No</a><button type="submit" class="btn btn--app">Borrar</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block extraJS %}

{% endblock %}

administrator/templates/products-list.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% block main-content-admin %}
    <div class="main-content__request--app">
        <div class="main-content__request__head">
            <h2>Este es el listado de los productos</h2>
            <a href="{% url 'administrator:product__add' %}" class="btn btn--app">Agregar producto</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="message message--info">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% for p in list_product %}
            {% if forloop.first %}
                <table class="list-products--app">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Variedad</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
            {% endif %}
                        <tr>
                            <td><img src="{{ MEDIA_URL }}{{ p.image }}" width="170" alt=""/></td>
                            <td>{{ p.variety }}</td>
                            <td>{{ p.features }}</td>
                            <td>{{ p.price|intcomma }} x {{ p.min_selling }} {{ p.sell_unit }}{{ p.min_selling|pluralize }}</td>
                            <td class="center"><a href="{% url 'administrator:product__delete' p.id %}"><img src="{% static 'images/delete_icon.png' %}" alt=""/></a></td>
                        </tr>
            {% if forloop.last %}
                    </tbody>
                </table>
            {% endif %}
        {% empty %}
            <h3>No hay productos</h3>
        {% endfor %}
    </div>
{% endblock %}

administrator/templates/request-detail.html
{% extends 'base_administrator.html' %}
{% load humanize %}
{% load cart_extras %}
{% block main-content-admin %}
    <div class="main-content__request--app request--detail">
        <h2>Este es el pedido <span>{{ order.code }}</span></h2>
        {% for i in order.orderitem_set.all %}

            {% if forloop.first %}
                <table>
                    <thead>
                        <tr class="fifth">
                            <th>Producto</th>
                            <th>Descripción</th>
                            <th>Precio unitario</th>
                            <th>Cantidad</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
            {% endif %}
                        <tr class="fifth">
                            <td><img src="{{ MEDIA_URL }}{{ i.product.image }}" alt="" width="170"/></td>
                            <td>{{ i.product.name }} {{ i.product.variety }}</td>
                            <td>$ {{ i.product.price }} x {{ i.product.min_selling }} {{ i.product.sell_unit }}{{ i.product.min_selling|pluralize }}</td>
                            <td>{{ i.quantity }}</td>
                            <td>$ {{ i.subtotal|intcomma }}</td>
                        </tr>
            {% if forloop.last %}
                    </tbody>
                </table>
            {% endif %}
        {% empty %}
            <h3>No hay pedidOS</h3>
        {% endfor %}
        <div class="totals">
{#            <div><p>Total productos </p><span>{{ order.subtotal|intcomma }}</span></div>#}
{#            <div><p>Total envio </p><span>2.650</span></div>#}
            <div class="great-total"><p>Total </p><span>{{ order.subtotal|intcomma }}</span></div>
        </div>
        <div class="shipping-info">
            <h2>Información de envío</h2>

            <p><span>Nombres</span>{{ order.buyer.name }}</p>

            <p><span>Correo</span>{%  if order.buyer.contact_email %}{{ order.buyer.contact_email }}{% else %}{{ order.buyer.user.email }}{% endif %}</p>

            <p><span>Dirección</span>{{ order.buyer.address }}</p>

            <p><span>Teléfono</span>{{ order.buyer.phone}}</p>
        </div>
    </div>
{% endblock %}

administrator/templates/request-list.html
{% extends 'base_administrator.html' %}
{% load static from staticfiles %}
{% load humanize %}

{% block main-content-admin %}
    <div class="main-content__request--app">
        <h2>Estos son los pedidos que han realizado</h2>
        <div id="message-change-request" class="message message--info"></div>
        <form action="." method="post" id="list-orders" class="transparent transparent--inline">
            {% csrf_token %}
            {{ list_orders.management_form }}
            {% for o in list_orders.forms %}
                {% if forloop.first %}
                    <table>
                    <thead>
                    <tr class="fifth">
                        <th>Referencia del pedido</th>
                        <th>Fecha de entrega</th>
                        <th>Precio total</th>
                        <th>Estado</th>
                    </tr>
                    </thead>
                    <tbody>
                {% endif %}
            <tr class="fifth">
                <td><a href="{% url 'administrator:request__detail' o.instance.id %}">{{ o.instance.code}}</a></td>
                <td>{{ o.id }}{% if o.shipping_date %}{{ o.shipping_date }}{% else %}Por definir{% endif %}</td>
                <td>$ {{ o.instance.subtotal|intcomma }}</td>
                <td>{{ o.state }}</td>
            </tr>
            {% if forloop.last %}
                </tbody>
                </table>
            {% endif %}
                {% empty %}
                <h3>No hay pedidOS</h3>
            {% endfor %}
        </form>
    </div>
{% endblock %}