buyer/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', orders_view, name='orders'),
    url(r'^micuenta/$', profile_view, name='home'),
]

comproagro/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from administrator import urls as admin_urls
from store import urls as store_urls
from website import urls as website_urls
from buyer import urls as buyer_urls



urlpatterns = [
    url(r'^', include(website_urls, namespace='website')),
    url(r'^tienda/', include(store_urls, namespace='store')),
    url(r'^administrador/', include(admin_urls, namespace='administrator')),
    url(r'^comprador/', include(buyer_urls, namespace='buyer')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    url(r'^salir/$', website_urls.logout_view, name='logout'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

store/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', store_view, name='home'),
    url(r'^add/$', add_product_car, name='add_to_car'),
    url(r'^delete/(?P<prod>\d+)/$', remove_product_car, name='remove_from_car'),
    url(r'^carrodecompra/$', show_car, name='show_car'),
    url(r'^hacerpedido/$', success_buy, name='make_request'),
    url(r'^detalle-producto/(?P<prod>\d+)/$', product_detail_view, name='product_detail'),
]

store/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from administrator.models import TimeStampModel, Buyer, Producer


SELL_UNIT = (
    ('kilo', 'Kilo'),
    ('libra', 'Libra'),
    ('caja', 'Caja'),
    ('unidad', 'Unidad'),
    ('arroba', 'Arroba'),
    ('bulto', 'Bulto'),
)
STATE_ORDER = (
    ('cancelado', 'Cancelado'),
    ('en proceso', 'En proceso'),
    ('enviado', 'Enviado'),
    ('pendiente', 'Pendiente'),
)


def upload_product_image(request, filename):
    return filename


@python_2_unicode_compatible
class Product(TimeStampModel):

    name = models.CharField(
        max_length=255,
    )
    variety = models.CharField(
        max_length=255
    )
    category = models.CharField(
        max_length=255
    )
    image = models.ImageField(
        upload_to=upload_product_image
    )
    sell_unit = models.CharField(
        max_length=16,
        choices=SELL_UNIT,
        default='kilo'
    )
    min_selling = models.PositiveIntegerField()
    price = models.FloatField()
    features = models.TextField()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        db_table = 'product'

    def __str__(self):
        return '%s' % self.name


@python_2_unicode_compatible
class Order(TimeStampModel):
    buyer = models.ForeignKey(
        Buyer,
        on_delete=models.PROTECT
    )
    producer = models.ForeignKey(
        Producer,
        null=True,
        blank=True
    )
    code = models.CharField(
        max_length=8
    )
    ship = models.FloatField()
    fee = models.FloatField()
    subtotal = models.FloatField()
    comments = models.TextField()
    state = models.CharField(
        max_length=50,
        choices=STATE_ORDER,
        default='pendiente'
    )
    shipping_date = models.DateField(
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        db_table = 'order'

    def __str__(self):
        return '%s' % self.code


@python_2_unicode_compatible
class OrderItem(models.Model):
    order = models.ForeignKey(
        Order
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT
    )
    quantity = models.PositiveIntegerField()
    subtotal = models.FloatField(
        blank=True
    )

    class Meta:
        verbose_name = 'Item pedido'
        verbose_name_plural = 'Items pedido'
        db_table = 'order_item'

    def __str__(self):
        return '%s-%s' % (self.order.code, self.product.name)

store/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms

from .models import Product, SELL_UNIT


class ProductForm(forms.ModelForm):
    sell_unit = forms.CharField(
        widget=forms.Select(
            choices=SELL_UNIT,
            attrs={
                'class': 'middle'
            }
        )
    )

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nombre'}),
            'variety': forms.TextInput(attrs={'placeholder': 'Variedad'}),
            'category': forms.TextInput(attrs={'placeholder': 'Categoria'}),
            'image': forms.FileInput(attrs={'class': 'jimage'}),
            'min_selling': forms.TextInput(attrs={
                'placeholder': 'Cantidad mínima', 'class': 'middle'
            }),
            'price': forms.TextInput(attrs={'placeholder': 'Precio'}),
            'features': forms.Textarea(attrs={'placeholder': 'Descripción del producto'})
        }
        labels = {
            'name': 'Nombre',
            'variety': 'Variedad',
            'category': 'Categoria',
            'image': 'Agregar imagen',
            'min_selling': 'Compra mínima',
            'price': 'Precio',
            'features': 'Descripción'
        }


class DeleteProductForm(forms.Form):
    prod = forms.CharField(
        max_length=50
    )

store/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from carton.cart import Cart
from django.template.loader import render_to_string

from administrator.models import UserModel, Buyer
from .models import Product, Order, OrderItem


def store_view(request):
    cart = Cart(request.session)
    list_varieties = Product.objects.values('variety').distinct()
    list_categories = Product.objects.values('category').distinct()

    # Get number items for page
    if request.GET.get('paginate_by') is None:
        items_by_page = 20
    else:
        items_by_page = int(request.GET.get('paginate_by'))

    # Filter for category and variety
    list_filter_category = []
    list_filter_variety = []
    for key, val in request.GET._iterlists():
        if key == 'category':
            for c in val:
                list_filter_category.append(c)
        if key == 'variety':
            for v in val:
                list_filter_variety.append(v)
    list_products = Product.objects.all()
    if list_filter_category:
        list_products = list_products.filter(category__in=list_filter_category)
        list_varieties = Product.objects.filter(category__in=list_filter_category).values('variety').distinct()
    if list_filter_variety:
        list_products = list_products.filter(variety__in=list_filter_variety)
        list_categories = Product.objects.filter(variety__in=list_filter_variety).values('category').distinct()

    # Number unique items in cart
    try:
        number_items = cart.unique_count
    except:
        number_items = 0

    # Order list products
    try:
        order_by = request.GET.get('order_by')
        if order_by == 'pasc':
            list_products = list_products.order_by('name', 'variety')
        elif order_by == 'pdes':
            list_products = list_products.order_by('-name', '-variety')
        else:
            list_products = list_products.order_by('id')
    except KeyError:
        order_by = ''
        list_products = list_products.order_by('id')

    # Pagination
    paginator = Paginator(list_products, items_by_page)
    page = request.GET.get('page')
    try:
        list_products = paginator.page(page)
    except PageNotAnInteger:
        list_products = paginator.page(1)
    except EmptyPage:
        list_products = paginator.page(paginator.num_pages)

    ctx = {
        'list_products': list_products,
        'list_varieties': list_varieties,
        'list_categories': list_categories,
        'list_filter_category': list_filter_category,
        'list_filter_variety': list_filter_variety,
        'number_items': number_items,
        'order_by': order_by,
        'items_by_page': items_by_page
    }

    return render(request, 'store_website.html', ctx)


def add_product_car(request):
    cart = Cart(request.session)
    product_item = Product.objects.get(id=request.GET.get('id'))
    if request.GET.get('quantity'):
        product_quantity = request.GET.get('quantity')
    else:
        product_quantity = product_item.min_selling
    cart.add(product_item, product_item.price, product_quantity)
    return HttpResponseRedirect(reverse_lazy('store:show_car'))

def remove_product_car(request, prod):
    cart = Cart(request.session)
    product_item = Product.objects.get(id=prod)
    cart.remove(product_item)
    return HttpResponseRedirect(reverse_lazy('store:show_car'))

def show_car(request):
    cart = Cart(request.session)
    total = cart.total
    ctx = {
        'total': total
    }
    return render(request, 'shopping_car.html', ctx)

def success_buy(request):
    cart = Cart(request.session)
    if request.user.is_authenticated():
        user = UserModel.objects.get(id=request.user.id, profile='comprador')
        try:
            buyer = Buyer.objects.get(user=user)
        except Buyer.DoesNotExist:
            pass
        order = Order()
        order.buyer = buyer
        order.state = 'pendiente'
        order.code = _generate_code()
        order.fee = 0
        order.ship = 0
        order.subtotal = cart.total
        order.comments = ''
        order.save()
        for item in cart.items:
            orderitem = OrderItem()
            orderitem.order = order
            orderitem.product = item.product
            orderitem.quantity = item.quantity
            orderitem.subtotal = item.subtotal
            orderitem.save()
        subject = 'Pedido ' + order.code
        msg_txt = render_to_string('email/order.txt', {'order': order})
        msg_html = render_to_string('email/order.html', {'order': order})
        list_recipents = settings.EMAIL_RECIPENT_LIST_CONTACT
        list_recipents.append(buyer.user.email)
        send_mail(
            subject,
            msg_txt,
            'info@comproagro.com',
            list_recipents,
            html_message=msg_html
        )
        request.session['CART'] = {}
        return HttpResponse(status=200)
    return HttpResponse(status=403)


def _generate_code():
    import random
    cart_id = ''
    characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
    cart_id_length = 8
    for y in range(cart_id_length):
        cart_id += characters[random.randint(0, len(characters) - 1)]
    return cart_id

def product_detail_view(request, prod):
    product = Product.objects.get(pk=prod)
    ctx = {
        'product': product
    }
    return render(request, 'product_detail.html', ctx)

store/templates/product_detail.html
{% extends 'base_website.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% load carton_tags %}
{% load cart_extras %}
{% block header %}
    <header class="header--buyer">
        {% include 'partials/head_website.html' %}
        <section class="head__content">
            <h1>Detalle de producto</h1>
        </section>
    </header>
{% endblock %}
{% block main_content %}
    <section class="main-content main-content--store-detail">
        <section class="product">
            <div class="product--image">
                <img src="{{ MEDIA_URL }}{{ product.image }}" alt=""/>
            </div>
            <div class="product--description">
                <h2 class="uppercase">{{ product.name }}</h2>
                <p class="product--subtitle">{{ product.variety }}</p>
                <p class="product--price"><span>{{ product.price|intcomma }}</span> x {{ product.min_selling }} {{ product.sell_unit }}{{ product.min_selling|pluralize }}</p>
                <p class="product--quantity-min">Compra mínima: <span>{{ product.min_selling }}</span> {{ product.sell_unit }}</p>
                <p class="product--text">{{ product.features }}</p>

                <form action="/tienda/add/" method="get" class="transparent">
                    <input type="hidden" name="id" id="id" value="{{ product.id }}"/>
                    <input class="product--quantity" type="number" min="{{ product.min_selling }}" name="quantity" id="quantity" value="{{ product.min_selling }}"/>
                    <button class="btn--app btn--app--left" type="submit">Comprar</button>
                </form>
            </div>
        </section>
        <section class="shipping--info">
            <h2>Información de envio</h2>
            <p>Comproagro entregara tus pedidos en la comodidad de tu casa entre 4 a 7 días hábiles, con pago contra entrega o consignación</p>
            <p><span>Contra entrega:</span> Los días de la promesa de venta, cuenta a partir de la confirmación de la compra.
                Para esto recibirá una llamada de servicio al cliente.</p>
            <p>
                <span>Consignación:</span> Una vez el banco ha aprobado la consignación y recibamos tu comprobante de pago al correo:
                comproagrocolombia@gmail.com. Servicio al cliente llamara a confirmar tu compra. Aplican restricciones y condiciones.
            </p>
            <ul>
                <li>Si la compra es confirmada después de las 5 de la tarde se registrara para el día siguiente.</li>
            </ul>
        </section>

    </section>
{% endblock %}

store/templates/shopping_car.html
{% extends 'base_website.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% load carton_tags %}
{% load cart_extras %}
{% block header %}
    <header class="header--buyer">
        {% include 'partials/head_website.html' %}
        <section class="head__content">
            <h1>Carrito de compras</h1>
        </section>
    </header>
{% endblock %}
{% block main_content %}
    <section class="main-content main-content--store">
        <section class="filter">

        </section>
        {% get_cart as cart %}
        <section class="products">
            <h2>Este es tu carrito de compras</h2>
            {% for p in cart.items %}
                {% if forloop.first %}
                    <table>
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Descripción</th>
                                <th>Precio unitario</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                {% endif %}
                            <tr>
                                <td><img src="{{ MEDIA_URL }}{{ p.product.image }}" alt="" width="170"/></td>
                                <td>{{ p.product.name}} {{ p.product.variety }}</td>
                                <td>{{ p.product.price|intcomma }} x {{ p.product.sell_unit }}</td>
                                <td>{{ p.quantity }}</td>
                                <td>{{ p.subtotal|intcomma }}</td>
                                <td><a href="{% url 'store:remove_from_car' p.product.id %}"><img src="{% static 'images/delete_icon.png' %}" /></a></td>
                            </tr>
                {% if forloop.last %}
                        </tbody>
                    </table>
                {% endif %}
            {% endfor %}
            <div class="totals">
{#                <div><p>Total productos </p><span>{{ total|intcomma }}</span></div>#}
{#                <div><p>Total envio </p><span>{{ 2650|intcomma }}</span></div>#}
                <div class="great-total"><p>Total </p><span>{{ total|intcomma }}</span></div>
            </div>
            <div class="buyer__actions">
                <button type="submit" id="make_request" class="btn--app">Hacer Pedido</button>
            </div>
        </section>
    </section>
    {% include 'partials/order-popup.html' %}
{% endblock %}

store/templates/store_website.html
{% extends 'base_website.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% load cart_extras %}
{% load carton_tags %}
{% block header %}
    <header class="header--buyer">
            {% include 'partials/head_website.html' %}
            <section class="head__content">
                <h1>Hacer mi pedido</h1>
                <div class="cart-items">
                    <a href="{% url 'store:show_car' %}">
                        {{ number_items }}
                    </a>
                </div>
            </section>
        </header>
{% endblock %}
{% block main_content %}
    <section class="main-content main-content--store">
        <section class="filter">
            <form action="." method="get" id="filter_store" class="transparent">
                <ul>
                    <li>
                        <p><span class="arrow--filter"></span> Producto</p>
                        <ul>
                            {% for c in list_categories %}
                                <li>
                                    <input type="checkbox" name="category" id="id_category_{{ c.category }}" value="{{ c.category }}" class="white"
                                            {% if c.category in list_filter_category %}checked{% endif %}/>
                                    <label for="id_category_{{ c.category }}">{{ c.category }}</label>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li>
                        <p><span class="arrow--filter"></span> Variedad</p>
                        <ul>
                            {% for v in list_varieties %}
                                <li>
                                    <input type="checkbox" name="variety" id="id_variety_{{ v.variety }}" value="{{ v.variety }}" class="white"
                                        {% if v.variety in list_filter_variety %}checked{% endif %} />
                                    <label for="id_variety_{{ v.variety }}">{{ v.variety }}</label>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </form>
        </section>
        <section class="products">
            <div class="filters">
                <select form="filter_store" class="select-filter" name="order_by" id="id_order_by">
                    <option value="">Ordenar por</option>
                    <option value="pasc" {% if order_by  == 'pasc' %}selected{% endif %}>Producto ascendente</option>
                    <option value="pdes" {% if order_by  == 'pdes' %}selected{% endif %}>Producto descendente</option>
                </select>
                <select form="filter_store" class="select-filter" name="paginate_by" id="id_paginate_by">
                    <option value="20" {% if items_by_page == 20 %}selected{% endif %}>20</option>
                    <option value="40" {% if items_by_page == 40 %}selected{% endif %}>40</option>
                </select>
            </div>
            <section class="products__list">
                {% for product in list_products %}
                    <article class="product__item">
                        <a href="{% url 'store:product_detail' product.id %}">
                            <figure class="product__item__image">
                                <img src="{{MEDIA_URL}}{{ product.image }}" alt="" width="170"/>
                            </figure>
                        </a>
                        <div class="product__info">
                            <h3 class="product__item__name">{{product.name}} {{ product.variety }}</h3>
                            <p class="product--price">
                                <span>{{ product.price|subtotal:product.min_selling|intcomma }}</span> x {{ product.min_selling }} {{ product.sell_unit }}{{ product.min_selling|pluralize }}
                            </p>
                            <form action="/tienda/add/" method="get" class="transparent">
                                <input type="hidden" name="id" id="id" value="{{ product.id }}"/>
                                <button class="btn--app btn--app--left btn--store " type="submit">Agregar</button>
                            </form>
                        </div>
                    </article>
                {% endfor %}
            </section>
            <div class="pagination">
                {% for page_num in list_products.paginator.page_range %}
                    <a href="{% append_to_get page=page_num %}">{{ page_num|subtotal:items_by_page }}</a>
                {% endfor %}
            </div>
        </section>
    </section>
{% endblock %}
{% block footer %}
    {% include 'partials/footer_website.html' %}
{% endblock %}